import "./globals.scss";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gamea",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

const RootLayout: React.FC<Props> = async ({ children }) => {
  return (
    <html lang="es">
      <body className={inter.className}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
