import "./globals.scss";
import { NextAuthProvider } from "./NextAuthProvider";

export const metadata = {
  title: "Gamea",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

const RootLayout: React.FC<Props> = async ({ children }) => {
  return (
    <html lang="es">
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
